### PR TITLE
Changes in the cheatsheet and icon qgisprocess

### PR DESCRIPTION
**Pull request by ambarja**

### CODE REVIEW

**Comment by ambarja** [comment]
@paleolimbot  the first icon had some error , but now it's ok and finally add cheatsheet in svg format 
error

**Comment by ambarja** [comment]
Well in this case is the same logo only was edited the png :)

**Comment by ambarja** [comment]
@paleolimbot  don't forget evaluate my pull request :)

**Comment by florisvdh** [comment]
Hi @ambarja, I'm catching up with the history of the logo and the cheatsheet! Thanks a lot for the amazing work you already did in this area! :rocket: :clap: 

Currently I see some issues:

- the new icon (announced in current PR) wasn't correctly set in the repo. So the figured icon (Readme, website) still has the problems you pinpointed [above](https://github.com/paleolimbot/qgisprocess/pull/45#issuecomment-824436085). I will fix that immediately; it appears that the new icon did not correctly replace the old one, but it _is_ present in the repo already :slightly_smiling_face:.
- the [cheatsheet](https://user-images.githubusercontent.com/23284899/109071088-4dbe1280-76c1-11eb-87df-b248494f2f01.png) you demoed [at Github](https://github.com/paleolimbot/qgisprocess/pull/34#issue-812512036) is not yet included in the repository. I'll be glad to add it to the repo.
  - However I believe this one is not even the latest version, considering the discussion in PR #34. Pasting the latest png or (better) svg here as a post, as @paleolimbot recommends, would be great!
  - It may need some further tweaks or additions anyway (considering the ongoing package updates), but I'll postpone my own review, so for now I propose to include the cheatsheet as-is since it's a great step forward!
  - After this package is on CRAN (hopefully by June), it would be great to contribute the cheatsheet as a PDF to https://posit.co/resources/cheatsheets. For now, we can include the cheatsheet as a figure in a separate vignette so that it appears on the **qgisprocess** website, much like **mapsf** does [here](https://riatelab.github.io/mapsf/articles/web_only/cheat_sheet.html).
  - At https://github.com/rstudio/cheatsheets/blob/main/.github/CONTRIBUTING.md are the templates and guidelines for cheatsheets to be contributed to Posit. You probably knew and used that, I'm just adding this to make sure.
- you're not yet listed among the package contributors; will be fixed immediately! :heart:

**Comment by ambarja** [comment]
Hi @florisvdh thanks for the comment, I'm glad the logo has been modified, regarding the cheatsheet, I have always considered the [R template guide cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/.github/CONTRIBUTING.md).
The original format is in a google cloud presentation, if you can share your gmail, I will be happy to give you access to the document, currently I have it in two languages, English and Spanish, maybe in the future it can be improved.

**Comment by florisvdh** [comment]
@ambarja, it's great that you maintain them in a repository! We can copy the png files to `vignettes/img` and follow **mapsf** in distributing both cheatsheets (en/es) as a vignette, including a direct link to the PDFs in your repo (until it has been distributed for Posit, after which that seems the preferred source). And we could explicitly refer your repo in the vignette if you like.

Those are things you can either do yourself (in a PR here) and let it be reviewed, or vice-versa (I copy, you review); your choice!

If you like, we could also harbour all files of the repo here, so that you can continue the maintenance of those files directly here. You choose!

Note: in filenames and folders I suggest to replace 'spa' by 'es' for consistency with 'en'; those are the [IETF BCP 47 language tags](https://www.w3.org/International/articles/language-tags/index.en).

And yes, it would be great to collaborate on the cheatsheet! I'd like to postpone that until further planned coding work on **qgisprocess** is done, although other contributors may also be interested in the meantime. You can share the google presentation with [my regular email address](https://github.com/paleolimbot/qgisprocess/blob/1515ca9493825faedec628e26c69e02d1ebc18b1/DESCRIPTION#L13) since it has a google account.

@paleolimbot please comment if you have any other preferences.

**Comment by ambarja** [comment]
@florisvdh delighted that this repository can be of reference in some vignettes, I know that there is much to improve this first attempt, right now I give you the access and I will modify the points touched.

**Pull request merged**
