### PR TITLE
Add the cheat sheets as vignettes and update website style

### PR DESCRIPTION
**Pull request by florisvdh**
Hi @ambarja, I gave this a try!

Follow-up from https://github.com/paleolimbot/qgisprocess/pull/45#issuecomment-1441950469.

You can have a look at the cheat sheet vignettes in the future **pkgdown** website by unpacking [pkgdown_site.zip](https://github.com/paleolimbot/qgisprocess/files/10852061/pkgdown_site.zip), opening `index.html`, and clicking 'Articles'.

All feedback (also by other contributors) is welcome.

I didn't intend to review or update the vignettes themselves, so this is just setting up some infrastructure to be able to advertise the cheat sheets from the package website. @ambarja If you feel that reviewing should happen first, then let me know, but I believe there's no harm in publishing as-is: just like the Readme and function documentation, all package documentation still needs a major rehaul.

There are two problems with the Spanish vignette:

- the few Spanish sentences are from Google Translate. Let me know what is to be improved, I don't speak Spanish unfortunately!
- the PDF link goes to `qgisprocess_es.pdf` in your repository, but that happens to be the same file as the English one. So you need to replace this file in your repo with the correct Spanish `qgisprocess_es.pdf`. Then the link will result in the correct cheat sheet.

Further, what would you prefer if people see an issue in a cheat sheet? Should they post it in this repo, or in your https://github.com/ambarja/cheatsheet-qgisprocess repo? I currently refer to your repo (as proposed), however it appears that 'Issues' are currently disabled in your repo. So let me know if this needs to change in the vignette, or not.

You can also propose changes to this PR directly in GitHub if you like, branching from this `cheatsheet` branch. Just then make sure that a new pull request refers to the `cheatsheet` branch (this PR) as its base.

### CODE REVIEW

**Comment by florisvdh** [comment]
@ambarja I've been experimenting a little with the hyperlink colours, to see if some QGIS colour could be used to replace the default blue one.

What do you think about this (didn't commit it yet) - to be compared with the [screenshot](https://github.com/paleolimbot/qgisprocess/pull/130#issuecomment-1450109569) of current state; see also the [pkgdown_site.zip](https://github.com/paleolimbot/qgisprocess/files/10861279/pkgdown_site.zip) since the hyperlinks turn 'QGIS-orange' when hovering:

image

**Comment by florisvdh** [comment]
Extra code for the hyperlink colour in the website is in a separate `pkgdown_green` branch for now, see commit 92ac307.

**Comment by florisvdh** [comment]
@paleolimbot @Robinlovelace and others: your ideas about the updated website style are most welcome!

**Comment by Robinlovelace** [comment]
Agreed, looks awesome from screenshot! Will take a look at the files changed now to see the substance...

**Comment by Robinlovelace** [comment]
Cheatsheets are awesome, so useful, big thumbs up from me after taking a look. I've not used `qgisprocess` for a while so not best placed to comment on contents.

**Comment by florisvdh** [comment]
Thanks for the replies; credits to @ambarja for the website upgrade!

**Comment by florisvdh** [comment]
Hi @ambarja can you have a look at some remaining questions:

- can you fix the latest logo in your repo since its subscript is not centered. This occurred in recent commit https://github.com/ambarja/cheatsheet-qgisprocess/commit/a0efbef; it is not yet included in `main` here, so I could also revert 3a69e7d in this PR and stick with previous version of logo.
- shall we implement the green hyperlinks as well?

Thanks again for these nice contributions!

**Comment by ambarja** [comment]
Hi @florisvdh I like your style proposal, I totally agree with you. On the other hand in my final version of my repository the logo is centered and in this pull-request I have put fixed logo with the name centered.
If I have to make a new pull-request, please let me know.
Thanks

**Comment by florisvdh** [comment]
Thank you very much @ambarja, I'll come back to this asap!!

**Comment by florisvdh** [comment]
Hi @ambarja considering the logo, the png (below left) is centered but the svg (below right) is not; see https://github.com/ambarja/cheatsheet-qgisprocess/blob/main/logo/qgisprocess.svg:

**Comment by florisvdh** [comment]
@ambarja after some odd observations of the rendered svg depending on the browser, I think we will have to resort to the png in order to have it rendered well cross-browser.

While the one-but-last svg shows centered text in Firefox, it does not in **Chrome**:

Schermafdruk van 2023-03-15 15-13-52

Also and even more striking, the same svg (currently in `main`) _on GitHub pages and in the Readme_ in **Firefox** is rendered as below _for a while_ (after which, e.g. by selecting it, it turns normal, i.e. with R), which we really can't have. I have no idea how this is possible, something which Firefox (currently) doesn't handle well, perhaps GitHub being involved too, browser state?... But definitely it is tied to the svg, will never happen with png.

Schermafdruk van 2023-03-15 15-11-06

With relation to 'centered or not', now I understand how our last discussion was confusing for both you and me. I am using Firefox, you may perhaps not. Anyway, here is a _screenshot_ of how I view the logos in [above post](https://github.com/paleolimbot/qgisprocess/pull/129#issuecomment-1459743566) (png left, svg right; notice they were rendered from the respective files in that post, so depending on the browser; they were not a static screenshot image pasted in the comment):

Viewed in **Firefox:** (screenshot!)

afbeelding

Viewed in **Chrome:** (screenshot!)

Schermafdruk van 2023-03-15 15-20-21

**Comment by ambarja** [comment]
Hi @florisvdh sorry for the late reply.
Regarding some bugs and the font type it was already fixed. You will find this in the latest push
inside my repository.
Here some views in different browser.

<table>
 <tr> 
     <td></td>
      <td></td>
      <td></td>
</tr>
   <tr align='center'>
     <td>Brave</td>
     <td>Firefox</td>
     <td>Edge</td>
   </tr>
<table>

**Pull request merged**
